{% set name = "types-contextvars" %}
{% set version = "2.4.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-contextvars-{{ version }}.tar.gz
  sha256: 0efa277afe8cd1d62fa7707835e3e49fab012db1bd3b749bf434c89a4dee382d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/contextvars-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for contextvars
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
